#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026-2036 Nicolas Van Eeckhout (founder) and Kern contributors
"""
build_v1_genesis.py
===================

Build the canonical Kern v1.0 genesis distribution from a config dict.
Produces two files:

- `genesis.json` — the chain-side initial state: balances, validators,
  treasury address, issuance params, governance state. This is what
  every node loads to bootstrap the chain.

- `genesis_vesting.json` — a side document describing vesting schedules
  for the founder pool, early contributors pool, and validator bootstrap
  pool. NOT enforced by the protocol in v1.0-rc; vesting is enforced
  off-chain by holding the locked KRN in a multisig and releasing per
  schedule. The on-chain protocol just sees the balances.

The total genesis supply is 100_000_000 KRN = 100_000_000_000_000 mukrn
(1 KRN = 1_000_000 mukrn).

Distribution (as agreed with the founder):
    Public sale         : 70_000_000 KRN  (70%)
    Founder (Nicolas)   : 10_000_000 KRN  (10%)  vested 4y/cliff 1y
    Foundation          : 15_000_000 KRN  (15%)
    Early contributors  :  3_000_000 KRN   (3%)  vested 3y/cliff 6mo
    Validator bootstrap :  2_000_000 KRN   (2%)  released over 1y
    -------------------------------------
    Total               : 100_000_000 KRN

Usage:
    python scripts/build_v1_genesis.py [--out genesis.json]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Make kern importable when run as script.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from kern.crypto import KernKeypair


MUKRN_PER_KRN = 1_000_000


# ---------------------------------------------------------------------------
# Distribution constants
# ---------------------------------------------------------------------------

TOTAL_SUPPLY_KRN = 100_000_000

PUBLIC_SALE_KRN = 70_000_000
FOUNDER_KRN = 10_000_000
FOUNDATION_KRN = 15_000_000
EARLY_CONTRIBUTORS_KRN = 3_000_000
VALIDATOR_BOOTSTRAP_KRN = 2_000_000

assert (
    PUBLIC_SALE_KRN + FOUNDER_KRN + FOUNDATION_KRN
    + EARLY_CONTRIBUTORS_KRN + VALIDATOR_BOOTSTRAP_KRN
) == TOTAL_SUPPLY_KRN


# Vesting schedules (in months from genesis).
VESTING_FOUNDER = {
    "cliff_months": 12,         # 1-year cliff: nothing released until month 12
    "vesting_months": 48,       # then linear over 4 years total
    "schedule_type": "linear_after_cliff",
}

VESTING_EARLY_CONTRIBUTORS = {
    "cliff_months": 6,
    "vesting_months": 36,
    "schedule_type": "linear_after_cliff",
}

VESTING_VALIDATOR_BOOTSTRAP = {
    "cliff_months": 0,
    "vesting_months": 12,
    "schedule_type": "linear_after_cliff",
}


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------

def derive_placeholder_address(seed_byte: int) -> tuple:
    """Derive a deterministic Ed25519 address for a genesis pool.

    For the founder, foundation, etc., a placeholder address is set in
    genesis. At launch, the corresponding seeds will be the actual
    multisig keys generated by the founder and foundation. The genesis
    file is regenerated then with the real addresses.

    Here we use deterministic seeds so the genesis file is reproducible
    across machines for testing."""
    kp = KernKeypair.from_seed(bytes([seed_byte]) * 32)
    return kp.address, kp.public_key_b58


def build_genesis() -> dict:
    """Build the canonical v1.0 genesis state."""

    founder_addr, founder_pk = derive_placeholder_address(0xF0)
    foundation_addr, foundation_pk = derive_placeholder_address(0xF1)
    contributors_addr, _ = derive_placeholder_address(0xF2)
    validator_bootstrap_addr, _ = derive_placeholder_address(0xF3)
    public_sale_addr, _ = derive_placeholder_address(0xF4)

    # First validator (bootstrap baker). Will be replaced at launch with
    # a Foundation-operated validator and 4 or 5 community validators.
    bootstrap_baker_addr, bootstrap_baker_pk = derive_placeholder_address(0xB0)

    balances = {
        public_sale_addr:            PUBLIC_SALE_KRN * MUKRN_PER_KRN,
        founder_addr:                FOUNDER_KRN * MUKRN_PER_KRN,
        foundation_addr:             FOUNDATION_KRN * MUKRN_PER_KRN,
        contributors_addr:           EARLY_CONTRIBUTORS_KRN * MUKRN_PER_KRN,
        validator_bootstrap_addr:    VALIDATOR_BOOTSTRAP_KRN * MUKRN_PER_KRN,
        # The bootstrap baker needs some stake to actually bake; this comes
        # from the Foundation pool on day 1 (the Foundation delegates 5M
        # KRN to the bootstrap baker until the validator set decentralizes).
        # We allocate it as own_stake here for simplicity.
    }

    # Bootstrap baker is registered as a validator. The Foundation
    # transfers it stake at launch; for the genesis file we put it at
    # 1M KRN to match a realistic launch configuration.
    bootstrap_stake_mukrn = 1_000_000 * MUKRN_PER_KRN  # 1M KRN
    balances[bootstrap_baker_addr] = bootstrap_stake_mukrn
    # This stake comes out of the Foundation's pre-launch allocation
    # (Foundation transferred it before genesis was signed).
    balances[foundation_addr] -= bootstrap_stake_mukrn

    validators = [{
        "address": bootstrap_baker_addr,
        "pubkey": bootstrap_baker_pk,
        "stake": bootstrap_stake_mukrn,
    }]

    total_supply_mukrn = TOTAL_SUPPLY_KRN * MUKRN_PER_KRN

    genesis = {
        "chain_id": "kern-mainnet-midgard",
        "genesis_time": "2027-Q3 (target)",
        "total_supply": total_supply_mukrn,
        "balances": balances,
        "validators": validators,
        "treasury_address": foundation_addr,
        # Issuance parameters: defaults from kern.issuance
        "issuance_params": {
            "i_min": 0.0025,
            "i_max": 0.06,
            "target_staking_ratio": 0.5,
            "block_time_seconds": 1.0,
            "treasury_share": 0.10,
            "proposer_bonus": 0.15,
        },
        # State-root function selection (json or trie). v1.0-rc launches
        # with trie active for light-client proof support.
        "state_root_function": "trie",
        # Pool address registry — useful for explorers and audits to label
        # the genesis pool addresses. Not consumed by the protocol.
        "pool_addresses": {
            "public_sale":         public_sale_addr,
            "founder":             founder_addr,
            "foundation":          foundation_addr,
            "early_contributors":  contributors_addr,
            "validator_bootstrap": validator_bootstrap_addr,
            "bootstrap_baker":     bootstrap_baker_addr,
        },
    }

    return genesis


def build_vesting() -> dict:
    """Build the off-chain vesting schedule document."""
    founder_addr, _ = derive_placeholder_address(0xF0)
    contributors_addr, _ = derive_placeholder_address(0xF2)
    validator_bootstrap_addr, _ = derive_placeholder_address(0xF3)

    return {
        "_doc": (
            "Vesting schedules for non-public pools. These are enforced "
            "off-chain by holding the locked KRN in a multisig and "
            "releasing per schedule. The protocol does NOT enforce vesting "
            "in v1.0-rc; on-chain balances appear immediately spendable. "
            "A future protocol amendment may add native vesting enforcement."
        ),
        "schedules": {
            "founder": {
                "address": founder_addr,
                "amount_krn": FOUNDER_KRN,
                **VESTING_FOUNDER,
                "recipient": "Nicolas Van Eeckhout (Kern founder)",
            },
            "early_contributors": {
                "pool_address": contributors_addr,
                "amount_krn": EARLY_CONTRIBUTORS_KRN,
                **VESTING_EARLY_CONTRIBUTORS,
                "recipient": "Foundation-managed pool, individual schedules per recipient",
                "individual_grants": [],  # populated as contributors are recognized
            },
            "validator_bootstrap": {
                "pool_address": validator_bootstrap_addr,
                "amount_krn": VALIDATOR_BOOTSTRAP_KRN,
                **VESTING_VALIDATOR_BOOTSTRAP,
                "recipient": "Foundation-managed pool, distributed to early validators",
                "individual_grants": [],
            },
        },
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    ap.add_argument("--out", default="genesis.json", help="Output genesis file path")
    ap.add_argument("--vesting-out", default="genesis_vesting.json",
                    help="Output vesting schedule path")
    args = ap.parse_args()

    genesis = build_genesis()
    Path(args.out).write_text(json.dumps(genesis, indent=2, sort_keys=True))
    print(f"Wrote {args.out}: 100M KRN distributed across 5 pools.")

    vesting = build_vesting()
    Path(args.vesting_out).write_text(json.dumps(vesting, indent=2, sort_keys=True))
    print(f"Wrote {args.vesting_out}: founder + contributor + validator schedules.")

    print()
    print("Distribution summary (KRN):")
    print(f"  Public sale         : {PUBLIC_SALE_KRN:>13,}")
    print(f"  Founder             : {FOUNDER_KRN:>13,}  (vested 4y / cliff 1y)")
    print(f"  Foundation          : {FOUNDATION_KRN:>13,}")
    print(f"  Early contributors  : {EARLY_CONTRIBUTORS_KRN:>13,}  (vested 3y / cliff 6mo)")
    print(f"  Validator bootstrap : {VALIDATOR_BOOTSTRAP_KRN:>13,}  (released over 1y)")
    print(f"  {'─' * 38}")
    print(f"  Total               : {TOTAL_SUPPLY_KRN:>13,}")


if __name__ == "__main__":
    main()
